Support BlurRadius
nagra-opentv/react-native-skia pull request #131
Opened 2022-07-07 10:13 UTC by ddesai96

Support BlurRadius
1. Skia's api "blur" is used for implementing, blurRadius.

2022-07-08 07:26 UTC, munezbn commented on ReactSkia/components/RSkComponentImage.cpp
> +    paint.setImageFilter(std::move(imageFilter));
This might overwrite previous ImageFilter if resizeMode was enabled.

2022-07-08 07:26 UTC, munezbn commented on ReactSkia/components/RSkComponentImage.cpp
> +    if(needClipAndRestore) canvas->restore();
Use braces as per new coding guideline

2022-07-15 04:56 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +#include "include/core/SkTileMode.h"
Please correct header file inclusion alphabetical order

2022-07-15 05:12 UTC, shefayaparwin requested changes

2022-07-15 05:12 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +#include "include/core/SkTileMode.h"
is this needed here ?? #include "include/core/SkTileMode.h" . It is already included in SkImageFilters.h. please check
SkImageFilters.h (include\effects):#include "include/core/SkTileMode.h" 

If needed, please correct the order of inclusion in alphabetical order

2022-07-15 05:12 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +      else {
Correct the indentation of else here

2022-07-15 05:12 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
>        /*TODO Not applied any shadow for solid Image when resizeMode is "Repeat"*/
IS this to do or a Bug: Please confirm. IF bug: remove TO do statement from here and record the Bug seperately

2022-07-15 05:12 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
>          sk_sp<SkImageFilter> imageFilter(SkImageFilters::Tile(targetRect,frameRect,layer()->shadowFilter));
can imageFilter name be changed to imageTileFilter to make it more meaningFull

2022-07-15 05:12 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +      } else if(contentShadow && imageProps.blurRadius) {
As this condition itself in  "contentShadow ", please remove teh redundant check from here

2022-07-16 13:39 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentImage.cpp
> +        shadowPaint.setImageFilter(std::move(imageBlurFilter));
can we optimize this code ?

2022-07-16 13:39 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentImage.cpp
> +    } else{
should this blur filter be set only if blurRadius prop is set

2022-07-16 13:39 UTC, pprabhu-ng commented on packages/react-native-skia/components/image/blurRadius.js
> +var blurRadius =[0,1,3,5,10,50,100,200,2000]
1. please also check negative values and when no blurRadius value is been set
2. check for jpg images as well
3. check with no shadow 
4. app is not checking tests with resizeMode

2022-07-18 14:31 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +      imageFilter ? shadowPaint.setImageFilter(std::move(imageFilter)) : shadowPaint.setImageFilter(layer()->shadowFilter);
Can we change set filter filter based on if/else logic. if(imageFilter) set ImageFilter, elseif(shadow filter) set shadowfilter.
 Which avoid setting of nullfilter.

2022-07-18 14:31 UTC, shefayaparwin approved these changes

2022-07-18 16:05 UTC, munezbn commented on ReactSkia/components/RSkComponentImage.cpp
> +        imageFilter = imageFilter ? SkImageFilters::Blur(imageProps.blurRadius, imageProps.blurRadius,imageFilter) : SkImageFilters::Blur(imageProps.blurRadius, imageProps.blurRadius,layer()->shadowF
Can we simply
SkImageFilters::Blur(imageProps.blurRadius, imageProps.blurRadius,(imageFilter ? imageFilter : layer()->shadowFilter) )

2022-07-18 16:05 UTC, munezbn commented on ReactSkia/components/RSkComponentImage.cpp
> +    paint.setImageFilter(std::move(imageFilter));
Dont we need imageFilter check  here ?

2022-07-20 05:46 UTC, pprabhu-ng commented on packages/react-native-skia/components/image/blurRadius.js
> +  return (
based on the changes , below cases need to be verified in the test app .please confirm 
a) blur radius + no background color + shadow 
b) blur radius + no background color + no shadow 
c) blur radius + background color + shadow 
d) blur radius + background color + no shadow 
e) all the above with no blur radius 
f) all the above with no blur radius + repeat resize mode

2022-07-20 07:38 UTC, ddesai96 commented on packages/react-native-skia/components/image/blurRadius.js
> +  return (
Tested and verified all test cases.

2022-07-20 07:39 UTC, pprabhu-ng approved these changes

2022-07-20 13:23 UTC, munezbn commented on ReactSkia/components/RSkComponentImage.cpp
> +      if(imageProps.blurRadius >= 0) {
DO we have to create filter for value 0 ?

2022-07-20 13:29 UTC, munezbn approved these changes

2022-07-20 13:41 UTC, chatrapathi06 approved these changes

2022-07-21 04:00 UTC, pprabhu-ng approved these changes

2022-07-21 04:01 UTC, merged