Networking xhr
nagra-opentv/react-native-skia pull request #135
Opened 2022-07-19 05:37 UTC by Dileepnidi

Cache manager implementation.

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/BUILD.gn
> +    "sdk/RSKCache.h",
DOnt add RSK prefix to SDK modules. Use **ThreadSafeCache**

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +      //delete networkRequest;
With shared pointer this can be solved.

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +        canCacheData_ = true;
Don't need this

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +  else if(cacheControlData.find("max-age=0") != std::string::npos) return false;
We can have spaces like "max-age =0" so comparing max-age=0 is risky

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +           responseMaxAgeTime = getCacheMaxAgeDuration(responseCacheControlString);
This function can be combined with shouldCacheData and pass max age as out parameter.

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +  self->RSkThreadSafeCache_->setCache(key, cacheData);
We don't need self, It can directly access.

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +  valueFactory cacheData;
Create structure with constructor with initializer list. And can remove this function itself

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +    for( auto const &header : Factory.headerBuffer.items()){
This for loop needs to be inside debug macro check

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +    for( auto const &header : Factory.headerBuffer.items()){
We can store curlResponse into cache and simply this function.

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/RSKCache.h
> +
Not required

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/RSKCache.h
> +  NetworkCacheMap networkCacheMap_;
Name should not contain Network. This is a generic cache implementation.

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/RSKCache.h
> +typedef facebook::better::map <string,valueFactory> NetworkCacheMap;
This has to be based on template

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/RSKCache.h
> +    networkCacheMap_[key].expiryTime = value.expiryTime;
cacheMap_[key].value = value;

2022-07-19 13:49 UTC, munezbn commented on ReactSkia/sdk/RSKCache.h
> +  void evict() {};
Add RNS_LOG_NOT_IMPL;

2022-07-22 17:16 UTC, pprabhu-ng requested changes

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/BUILD.gn
> +    "sdk/ThreadSafeCache.h",
the file to be included in alphabetical order

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +  curlRequest->curlResponse = make_shared<CurlResponse>();
can this be done in contructor of curlRequest itself ?

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.cpp
> +  RSkThreadSafeCache_ = new RSkThreadSafeCache<string,shared_ptr<CurlResponse>>(10,12);
Can we add this number as a define.
Why cant these values be handled by the RSkThreadSafeCache ?
If there is no values provided, the RSkThreadSafeCache can configure a default value.

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.cpp
> +inline bool shouldCacheData(std::string cacheControlData, double* expiryTime) {
should we add this function under curlResponse or curlRequest ?
it wil help clients to reuse the same code. For example Image component today has the same code, instead it can use the function defined in this sdk module itself. To avoid duplication and maintainability.

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.cpp
> +        cacheExpiryTime_ = DEFAULT_MAX_CACHE_EXPIRY_TIME;
can all these logic of cache (line 101 - 107) related go under shouldCacheData function ?

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.cpp
> +            RSkThreadSafeCache_->setCache(url, curlRequest->curlResponse);
is it setCache or insertToCache ?

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.cpp
> +        cacheExpiryTime_ = std::min(std::min(responseMaxAgeTime,requestMaxAgeTime),static_cast<double>(DEFAULT_MAX_CACHE_EXPIRY_TIME));
what is the purpose of cacheExpiryTime_ variable here ? it seems to be not used. If required , should it be under curlResponse object ?

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.cpp
> +            RSkThreadSafeCache_->setCache(url, curlRequest->curlResponse);
Use case :
Two objects requesting for same url parallely
First request processed and added to cache.
Second request for some reason failed. 
In this case , we will be overwriting the success data with error data in the cache. 

So should we check before adding to cache here ?

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.cpp
> +  curlRequest->curlResponse = RSkThreadSafeCache_->getCache(Key);
should this be getCache or getCacheData ?

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.cpp
> +  if(curlRequest->curlResponse->headerBuffer != NULL) {
NULL to be replaced with nullptr ? 
comment applicable at all places in the PR

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.cpp
> +    sendResponseCacheData(curlRequest, curlRequest->URL);
getCache() is already doing this operation. do we need to do it again here

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.cpp
> +    return true;
if responseBuffer and headerBuffer is nullptr, should we process the request instead of return true for this case.

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.cpp
> +  RSkThreadSafeCache_ = new RSkThreadSafeCache<string,shared_ptr<CurlResponse>>(10,12);
should we have a diff name for this variable RSkThreadSafeCache_, since this cache is related to Network data

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.h
> +  RSkThreadSafeCache<std::string, shared_ptr<CurlResponse> >*  RSkThreadSafeCache_;
should this RSkThreadSafeCache_ be private ?

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.h
>    folly::dynamic headerBuffer;
CurlResponse destructor need to handle freeing of responseBuffer data ?

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/ThreadSafeCache.h
> +namespace facebook {
namespace to be rns::sdk ?

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/ThreadSafeCache.h
> +  std::mutex CacheLock;
variable name to follow guidelines

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/ThreadSafeCache.h
> +    return cachedData;
if iterator is end() , we need to return nullptr right ?

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/ThreadSafeCache.h
> + private:
can we add comment for the variables, what each value represents .
It will be helpful for using the template in other modules/components

2022-07-22 17:16 UTC, pprabhu-ng commented on ReactSkia/sdk/ThreadSafeCache.h
> +  better::map <KeyT,ValueT> CacheMap_;
should the CacheMap_ be private ?

2022-07-25 15:00 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +  //Currently sending dummy values for testing, Original values will be updated as part of handling eviction.
Replace comment with : // TODO Values will be updated when we added eviction logic

2022-07-25 15:00 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +    else if(maxAgePos != std::string::npos) {
This block needs to be optimised. And also we have to tokenize "max-age = 0" and read the value.

2022-07-25 15:00 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +            }
Indentation.

2022-07-25 15:00 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +    isCachedResponse = false;
No need of this else case.

2022-07-25 15:00 UTC, munezbn commented on ReactSkia/sdk/CurlNetworking.cpp
> +    return true;
This call will happen in callers thread, unlike other request which are not cached (yet). Better to do this dispatch in another thread ?

2022-07-25 15:00 UTC, munezbn commented on ReactSkia/sdk/ThreadSafeCache.h
> +  bool findCache(const char* url){
What is purpose of this this function ?  This cannot be non-generic right ? May be you meant to use KeyT for searching ? 
Either use name isAvailableinCache(keyT) or We can re-purpose getCacheData() for checking also

2022-07-25 16:45 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.h
> +  RSkThreadSafeCache<std::string, shared_ptr<CurlResponse> >*  NetworkCache_;
variable name to follow case guidelines

2022-07-25 16:53 UTC, pprabhu-ng commented on ReactSkia/sdk/ThreadSafeCache.h
> +class RSkThreadSafeCache {
should the name of the class be similar to filename ? without RSk prefix ?

2022-07-25 16:53 UTC, pprabhu-ng commented on ReactSkia/sdk/ThreadSafeCache.h
> +//RSkThreadSafeCache<string,shared_ptr<CurlResponse>>
is this comment valid ?

2022-07-25 16:53 UTC, pprabhu-ng commented on ReactSkia/sdk/CurlNetworking.h
> +  double cacheExpiryTime_{DEFAULT_MAX_CACHE_EXPIRY_TIME};
"_" postfix not required for this public variable

2022-07-29 10:26 UTC, Dileepnidi commented on ReactSkia/sdk/CurlNetworking.cpp
> +          else {
Indentation

2022-08-02 05:06 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentImage.cpp
> +    remoteCurlRequest->curldelegator.CURLNetworkingHeaderCallback = nullptr;
instead of resetiing this function pointer in its call , can it be done in sdk itself after the function is called ?

2022-08-02 09:18 UTC, pprabhu-ng approved these changes

2022-08-02 11:39 UTC, ddesai96 approved these changes

2022-08-02 12:28 UTC, chatrapathi06 approved these changes

2022-08-02 12:31 UTC, munezbn approved these changes

2022-08-05 18:06 UTC, merged