Improvement in Image Shadow
nagra-opentv/react-native-skia pull request #151
Opened 2022-09-01 17:58 UTC by ddesai96

Improvement in Image Shadow

2022-10-25 06:49 UTC, shefayaparwin commented on ReactSkia/components/RSkComponent.cpp
> +      createShadowFilter=true;
createShadowFilter to be false to Reset the shadowFilter.

2022-10-25 06:53 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +#include "include/core/SkMaskFilter.h"
Header file order to be corrected as per coding guide Lines [Alphabetical order]

2022-10-25 06:59 UTC, shefayaparwin commented on ReactSkia/components/RSkComponent.cpp
>     /* Create shadow filter - shadow opacity is not 0 and change in any props of shadow - opacity,offset,radius */
Can this comment be updated to reflect the changes .

Resetting shadow filter here on below scenario  and creation/Re-creation happens in components:

- when Shadow won't be visible outside the component., where shadow is directly under the component [Shadow Offset as Zero]
- Shadow is fully transparent
- Shadow will be visible , but it's property have changed.

2022-10-25 07:01 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.h
> +  inline void drawContentShadow(SkCanvas *canvas,
Can we provide description  of input argument alongside

2022-10-25 07:15 UTC, shefayaparwin commented on rns_shell/compositor/layers/Layer.cpp
> +        if(componentShadow.imageFilter) {
condition needs to be Either maskFilter or ShadowFilter exist

componentShadow.imageFilter || componentShadow.maskFilter

2022-10-25 07:17 UTC, shefayaparwin commented on rns_shell/compositor/layers/Layer.h
> +        RNS_LOG_INFO("createImageFilter");
Can this debug be removed

2022-10-25 07:17 UTC, shefayaparwin commented on rns_shell/compositor/layers/Layer.h
> +        RNS_LOG_INFO("createMaskFilter");
Can this debug be removed

2022-10-25 07:24 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +                                                      bool setImageShadowFilter, bool isOpaque) {
Can this be changed to filterForShadow to reflect the purpose & usage.
Currently setImageShadowFilter set as true for deawshadow & flase for DtawImage. Which contradicting the variable name

2022-10-27 18:33 UTC, shefayaparwin commented on ReactSkia/components/RSkComponent.cpp
> +      (!layer_->componentShadow.isShadowVisible())|| (!resetShadowFilter) ) {
As flag is Reset, Rest needs to be doen when resetShadowFilter is set.
So instead of (!resetShadowFilter) , it have to be (resetShadowFilter)

2022-10-27 18:35 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +    filterForShadow(paint,imageProps,targetRect,frameRect,false,imageData->isOpaque());
Comment given to change the argument name in setImageFilters, not to chnage the function name

2022-10-28 03:10 UTC, shefayaparwin requested changes
When component[view,image,....] is transparent, then shadow beneath will be visible. 
Considering this scenario , clipping to be done for shadow drawing, only when it's component is not transparent.
So we can add APi, is component transparent in "ComponentShadow" structure of Layer & use it while clipping

2022-10-28 03:13 UTC, shefayaparwin commented on rns_shell/compositor/layers/Layer.h
> +struct ComponentShadow {
Can add Api to get component to which shadow to be drawn is transparent or NOt as part of this structure:
bool isComponentTransparent() {
   return (opacity < 0xFF);
}

2022-10-28 03:14 UTC, shefayaparwin commented on ReactSkia/views/common/RSkDrawUtils.cpp
>  bool  drawShadow(SkCanvas *canvas,Rect frame,
Add additional input argument "bool shadowOnTransparentComponent". Which to be used before clipping

2022-10-28 03:17 UTC, shefayaparwin commented on ReactSkia/views/common/RSkDrawUtils.cpp
> +        bool needsSaveLayer=(componentShadow.shadowOpacity|| (shadowOn == Background));
condition to be changed to
 bool needsSaveLayer=(componentShadow.shadowOpacity|| ((shadowOn == Background) && !shadowOnTransparentComponent));

2022-10-28 03:17 UTC, shefayaparwin commented on ReactSkia/views/common/RSkDrawUtils.cpp
> +        if(shadowOn == Background) {
Here as well, clipping need only for opaque component

if((shadowOn == Background) && !shadowOnTransparentComponent)

2022-10-28 03:30 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +        canvas->saveLayer(&shadowRect,&shadowPaint);
Here also need to set "SaveLAyerDone=true" as SaveLayer been done Here. Also this blocks needs to changed as below to consider component/Image opacity

REwritting else case as below


!componentShadow.isComponentTransparent

2022-10-31 09:44 UTC, shefayaparwin commented on ReactSkia/views/common/RSkDrawUtils.cpp
> +printf("\n@@@####@@## shadow draw  \n");
Remove This !!!

2022-10-31 09:57 UTC, shefayaparwin commented on rns_shell/compositor/layers/Layer.h
> +struct ComponentShadow {
As Discussed, No Need for Seperate API to get component transparency. But i see there many place !(opacity < 0xFF) is been used. It doesn't explain directly the purpose.
To make it meaning and handy. suggest to maintain a flag in Layer class to get the component transparency. and use it. That sounds more sensible for below reason 

- repeating this handling in many place "(opacity < 0xFF)"
- Passing bool is better than  float value

YOu can address this comment , in the end. Once you get a feedback cumulative feedback.
Summarizing Open Feedback Here from @pprabhu-ng :-

1. componentShadow, can be defined as Nested class for LAyer
2. structure Name componentShadoe to be changed, as it is part of Layer.

2022-10-31 10:02 UTC, shefayaparwin approved these changes
### Approving  with the consideration, below would be handled once, review happened from other reviewers.

- As Discussed, No Need for Seperate API to get component transparency. But i see there many place !(opacity < 0xFF) is been used. It doesn't explain directly the purpose.

To make it meaning and handy. suggest to maintain a flag in Layer class to get the component transparency. and use it. That sounds more sensible for below reason

1. Instead of repeating this handling in many place "(opacity < 0xFF)"
2.  Passing bool is better than float value

YOu can address this comment , in the end. Once you get a feedback cumulative feedback.
### Summarizing Open Feedback Here from @pprabhu-ng :-

1. componentShadow, can be defined as Nested class for LAyer
2. structure Name componentShadoe to be changed, as it is part of Layer.

2022-11-10 06:25 UTC, shefayaparwin commented on ReactSkia/views/common/RSkDrawUtils.cpp
> +        /* Border Color  differs for each Side.So make sure all the side are Visible*/
Instead of "So make sure all the side are Visible*"--> make it as check

2022-11-10 06:49 UTC, shefayaparwin commented on ReactSkia/views/common/RSkDrawUtils.cpp
> +        /* Border Color  differs for each Side.So make sure all the side are Visible*/
Create an inline function "hasVisibleBorder" , which check attest of width is none zero, and at least one side color is not transparent. And make this as a first condition.

2022-11-10 06:51 UTC, shefayaparwin commented on ReactSkia/views/common/RSkDrawUtils.cpp
> +            if(isDrawVisible(borderProps.borderColors.left,borderProps.borderWidths.left) &&
With teh new approach, just need to validate colors and not width. SO can make a seperate inline Api to validate color

2022-11-10 11:05 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentTextInput.cpp
> +  if(layerRef->shadowVisibility) {
can rename this to "isShadowVisible"

2022-11-10 11:56 UTC, shefayaparwin commented on ReactSkia/components/RSkComponent.cpp
> +bool RSkComponent::getshadowVisibility() {
Rename as "needsShadowPainting"

2022-11-10 12:01 UTC, shefayaparwin commented on rns_shell/compositor/layers/Layer.cpp
> +    if(shadowImageFilter) {
use elseif
Add comments in cases

2022-11-10 12:10 UTC, shefayaparwin commented on rns_shell/compositor/layers/Layer.cpp
> +inline SkIRect Layer::getFrameBoundsWithShadow(const SkIRect origSrc){
Directly access frame here , no need of argument

2022-11-10 12:15 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +inline void RSkComponentImage::setImageFilters (SkPaint &paintObj,const ImageProps &imageProps,
rename . setPaintFilters

And add comment ["This function apply appropriate filter on paint object to draw image & Shadow"]

2022-11-10 12:54 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +inline void RSkComponentImage::drawContentShadow( SkCanvas *canvas,
Add To DO for :When Frame doesn't have background, has border with Jpeg Image and no resize. currently drawing shadow for both border and content. Need to cross verify with reference and confirm the behaviour.

2022-11-10 12:56 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +  } else {
Add comment as shadow on content

2022-11-14 06:00 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +           So returning false.
Change the comment here to reflect teh condition. instead of "So returning false." change it to "So returning true."

2022-11-14 06:00 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentImage.cpp
> +       (resizeMode == ImageResizeMode::Repeat)) /* IN repeat mode,Image will be repaeted to fill the frame */ {
Typo error :"repaeted "--> "repeated "

2022-11-14 12:30 UTC, pprabhu-ng commented on rns_shell/compositor/layers/Layer.cpp
> +        SkRect ShadowRect=SkRect::MakeXYWH(frame_.x()+shadowOffset.width(), frame_.y()+shadowOffset.height(), frame_.width(), frame_.height());
variable name need to be small letters ?

2022-11-14 13:13 UTC, munezbn approved these changes

2022-11-14 13:22 UTC, pprabhu-ng commented on rns_shell/compositor/layers/Layer.cpp
>              SkMatrix identityMatrix;
redundant line can be removed right ?

2022-11-14 13:22 UTC, pprabhu-ng commented on rns_shell/compositor/layers/Layer.cpp
> +        if(isShadowVisible) {
do we need isShadowVisible in Layer ?
this can be achived by just shadowImage/Mask filter itself ?

2022-11-14 13:22 UTC, pprabhu-ng commented on packages/react-native-skia/components/image/ImageShadowImprovement.js
> +import * as React from 'react';
file name to be renamed based on the use case verified in this test app

2022-11-14 13:22 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponent.cpp
> +   layer_->isShadowVisible=needsShadowPainting();
is needsShadowPainting , then shadow image/mask filter needs to be created . else it needs to be reset right ?

2022-11-14 13:22 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentImage.cpp
> +  bool SaveLayerDone=false;
variable name to follow small letters

2022-11-14 13:25 UTC, ddesai96 commented on rns_shell/compositor/layers/Layer.cpp
>              SkMatrix identityMatrix;
yes

2022-11-14 13:51 UTC, pprabhu-ng approved these changes

2022-11-14 13:53 UTC, chatrapathi06 approved these changes

2022-11-14 14:34 UTC, merged