Changes According Coding Guidelines & Compilation Error
nagra-opentv/react-native-skia pull request #31
Opened 2021-08-11 10:55 UTC by chatrapathi06

Changes according the coding guild lines

2021-08-12 15:57 UTC, pprabhu-ng requested changes

2021-08-12 15:57 UTC, pprabhu-ng commented on ReactSkia/sdk/RNSKeyCodeMapping.h
> +    "audioReacord",
spell-check - audioRecord

2021-08-12 15:57 UTC, pprabhu-ng commented on ReactSkia/sdk/RNSKeyCodeMapping.h
> +    "unKown"
spellcheck - unknown

2021-08-12 15:57 UTC, pprabhu-ng commented on ReactSkia/sdk/RNSKeyCodeMapping.h
> +    "audioStop",
regarding these key names , we may have to revisit these strings similar to Android key names . Refer - https://github.com/react-native-tvos/react-native-tvos/commit/b3d81dfd8604263671b9e006f8f00786b0f8fcfb#

2021-08-16 08:48 UTC, pprabhu-ng approved these changes

2021-08-19 04:59 UTC, munezbn approved these changes

2021-08-19 05:28 UTC, merged