Key mapping for alpha and symbolic keys
nagra-opentv/react-native-skia pull request #37
Opened 2021-08-26 06:12 UTC by chatrapathi06

Key mapping for alpha and symbolic keys for Keyboard Keys in  X11 and LibWpe

2021-08-26 07:12 UTC, pprabhu-ng requested changes
@chatrapathi06  its better to keep the RNS key names similar to WPE .
Ensure spelling checks for the keys.

2021-08-26 14:27 UTC, pprabhu-ng requested changes

2021-08-26 14:27 UTC, pprabhu-ng commented on ReactSkia/sdk/RNSKeyCodeMapping.h
> +    RNS_KEY_Dolar,
should be RNS_KEY_Dollar ?

2021-08-26 14:27 UTC, pprabhu-ng commented on ReactSkia/sdk/RNSKeyCodeMapping.h
> +    RNS_KEY_Braceleft,
Braceleft/right to be defined similar to other keys

2021-08-26 14:27 UTC, pprabhu-ng commented on ReactSkia/sdk/RNSKeyCodeMapping.h
> +    "UnKnown"
need to maintain consistency in defining the strings for the keys.
few keynames are camelcase, few are pascal case.

2021-08-30 05:08 UTC, munezbn commented on packages/react-native-skia/modules/tvEventHandler/tvEventHandler.js
> +      console.log('APP: TV Key event received:  [evt.eventType]',  evt.eventType);
Now we can also print eventKeyAction, tag and target

2021-08-30 05:08 UTC, munezbn commented on rns_shell/platform/graphics/x11/X11KeyMap.cpp
> +#include "ReactSkia/utils/RnsLog.h"
can we move up before line 3

2021-09-01 07:26 UTC, pprabhu-ng approved these changes

2021-09-02 06:19 UTC, munezbn approved these changes

2021-09-03 05:52 UTC, merged