Networking changes for events onError, onLoad, onTimeout
nagra-opentv/react-native-skia pull request #38
Opened 2021-08-26 06:38 UTC by Dileepnidi

implemented changes  for Networking events onError, onLoad, onTimeout

2021-08-26 08:11 UTC, pprabhu-ng requested changes

2021-08-26 08:11 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +            sendEventWithName(events_[0], folly::dynamic::array(requestId_,curl_easy_strerror(res), false));
is this required to be in else condition ?
for timeout here it sends two events one with timeout flag as true and another event with false.

2021-08-26 08:11 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +        curl_easy_getinfo (curl, CURLINFO_RESPONSE_CODE, &http_code);
seems http_code is not been used ...

2021-08-26 08:11 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.h
> +static int requestId_;
is this required to be static ? can it be local variable , since the value wll be already in hash map

2021-08-26 08:11 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.h
> +        std::vector<std::string> events_ = {"didCompleteNetworkResponse","didReceiveNetworkData"};
do we need to store these strings in class object ?
can we directly use the string for the events ?

2021-08-26 08:11 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +        connectionList_[requestId_] = curl;
we have to use std::move or shared pointer here  for curl ?

2021-08-26 14:17 UTC, pprabhu-ng requested changes

2021-08-26 14:17 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +  int requestId =0;
should be of type uint64_t ? since nextUniqueId() returns uint64_t

2021-08-27 07:54 UTC, pprabhu-ng approved these changes

2021-08-30 04:54 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +#define CURL_RETURN_FAILURE -1
Can we use enum instead.

2021-09-02 07:01 UTC, munezbn approved these changes

2021-09-03 05:52 UTC, merged