Netwoking abort api, event and send callback implementation
nagra-opentv/react-native-skia pull request #42
Opened 2021-09-07 04:27 UTC by Dileepnidi

Netwoking abort api, event and send callback implementation

2021-09-07 11:43 UTC, pprabhu-ng requested changes

2021-09-07 11:43 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> + connectionList_[requestId.asInt()] = curl;
why is this assignment required here ?

2021-09-08 07:33 UTC, munezbn requested changes
Just confirm if abort works in case where request is blocked.
Also update the abort error message

2021-09-15 04:35 UTC, pprabhu-ng approved these changes

2021-09-15 04:52 UTC, munezbn reviewed
Check the indentation once  before merging.

2021-09-16 05:44 UTC, munezbn approved these changes

2021-09-16 08:56 UTC, merged