Added Input Event Manager & TextInput Components to RNS
nagra-opentv/react-native-skia pull request #58
Opened 2021-10-25 12:56 UTC by chatrapathi06

1.  Added Input Event Manager & Text-Input Components to RNS
2. Text-input only onKeypress event is handled.

2021-10-27 17:18 UTC, pprabhu-ng requested changes

2021-10-27 17:18 UTC, pprabhu-ng commented on ReactSkia/BUILD.gn
> +
whether image and imagemanager is required as dependency ?

2021-10-27 17:18 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponent.cpp
>  }
there is no change in this file. need to remove if no changes

2021-10-27 17:18 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +#include <string.h>
sequence of header file includes to follow guidelines

2021-10-27 17:18 UTC, pprabhu-ng commented on ReactSkia/RSkSurfaceWindow.cpp
>    navigator_ = RSkSpatialNavigator::sharedSpatialNavigator();
since InputEventManager would initialize the spatial navigator, whether we require it here ?

2021-10-27 17:18 UTC, pprabhu-ng commented on ReactSkia/textinput/react/renderer/components/textinput/TextInputComponentDescriptor.h
> +  SharedTextLayoutManager textLayoutManager_;
If we have done this change, then we have add our  copyright  also in copyright section

2021-10-27 17:18 UTC, pprabhu-ng commented on ReactSkia/textinput/react/renderer/components/textinput/TextInputProps.cpp
> +#ifdef ANDROID
since this condition is not applicable for RNS, can we remove this code

2021-10-27 17:18 UTC, pprabhu-ng commented on ReactSkia/textinput/react/renderer/components/textinput/TextInputState.cpp
> +namespace react {} // namespace react
if there is no functionality in this file , whether its required?

2021-10-27 17:18 UTC, pprabhu-ng commented on ReactSkia/textinput/react/renderer/components/textinput/primitives.h
> +   * iOS & Android
should be add RNS :)

2021-11-01 13:44 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +	RNS_LOG_TODO("send onchange and onchangetext here");
this log is out of indentation ?

2021-11-01 17:58 UTC, munezbn requested changes

2021-11-01 17:58 UTC, munezbn commented on ReactSkia/core_modules/RSkSpatialNavigator.cpp
>      // First send keyevent to TVNavigation Emitter
Remove comment     // First send keyevent to TVNavigation Emitter

2021-11-01 17:58 UTC, munezbn commented on ReactSkia/core_modules/RSkInputEventManager.h
> +#include "react/renderer/components/textinput/iostextinput/TextInputEventEmitter.h"
why are we including iostextinput

2021-11-01 17:58 UTC, munezbn commented on ReactSkia/core_modules/RSkInputEventManager.cpp
> +  if(currentFocused){// if currentFocused is null, Key will is not handled.
Edit comment.

2021-11-01 17:58 UTC, munezbn commented on ReactSkia/core_modules/RSkInputEventManager.cpp
> +       *like bubling.
Need to correct this comment.  There can be cases where key is handled but stop propagating is false.

2021-11-01 17:58 UTC, munezbn commented on ReactSkia/components/RSkComponent.h
> +  virtual bool onHandleKey(rnsKey  eventKeyType){return false;};
Just to make it more clear the return value can  tell if key is handled or not and extra out parameter "stopPropagating" to be filled by component.

2021-11-01 17:58 UTC, munezbn commented on ReactSkia/core_modules/RSkInputEventManager.cpp
> +  /*when key pressed key press and key release events will be send.
Edit comment

2021-11-11 10:21 UTC, pprabhu-ng approved these changes

2021-11-11 11:41 UTC, munezbn requested changes

2021-11-11 11:41 UTC, munezbn commented on ReactSkia/components/RSkComponent.h
> +  virtual void onHandleKey(rnsKey  eventKeyType,bool* stopPropagate){return;};
we should assign false in stopPropagate

2021-11-11 14:13 UTC, munezbn approved these changes

2021-11-12 05:31 UTC, merged