Implementation for Networking Events
nagra-opentv/react-native-skia pull request #59
Opened 2021-10-28 12:16 UTC by Dileepnidi

Implementation for Networking XHR Events

2021-10-29 15:09 UTC, munezbn requested changes

2021-10-29 15:09 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +  ((struct NetworkRequest *)userdata)->self_->sendProgressEventwrapper(userdata,dltotal,dlnow,ultotal,ulnow);
For all the wrapper function convert userdata into NetworkRequest locally and pass that converted data as first argument, instead of sending userdata and converting again in warapper functions.

2021-10-29 15:09 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
>    return realsize;
It shouldn't return realsize here, It should return the return value of wrapper function which should return actually written size

2021-10-29 15:09 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +  size_t pos = std::string::npos;
You can use CURLINFO_CONTENT_LENGTH_DOWNLOAD instead to get content length

2021-10-29 15:09 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +        curl_easy_setopt(curl, CURLOPT_TIMEOUT, 10L);
use #define for default Timeout value.

2021-10-29 15:09 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +  {
do we need do to this in block ?

2021-10-29 15:09 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);//Enable curl logs
Should we keep it OFF by default

2021-10-29 15:09 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +    curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 0L); // Enable progress callback
I think we need to enable this only if incremental update is true right ?

2021-10-29 15:09 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +        std::scoped_lock lock(isMutating);
This lock should go before curl !=null  Check

2021-10-29 15:09 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +  long response_code;
initialize with default response code.

2021-10-29 15:09 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +  sendEventWithName("didReceiveNetworkResponse", folly::dynamic::array(networkRequest->requestId_  , response_code,  headerInfoBuffer ,url));
I think we need to send this signal only once with all headers

2021-10-29 15:09 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +    sendEventWithName("didReceiveNetworkData", folly::dynamic::array(networkRequest->requestId_  , networkRequest->responseBuffer_));
We need to make this as common for all three cases , Like IOS,
1. when it is text
2. when it is base64 text
3. As per IOS code they send this signal even when there is no resonseBuffer

2021-11-11 10:17 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.h
> +  std::mutex isMutating;
name should be diff for this mutex ?

2021-11-11 10:17 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +  } else if(data["uri"].c_str()) {
in RCTNetworking.js , there seems to be below types of data
1. string
2. formData
3. blob
4. base64  ==> arraybuffer type data 
5. others

should we add base64 ?

2021-11-11 10:17 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +        RNS_LOG_ERROR ("Unknown method\n") ;
in error string than "unknown" should this be not implemented ?
because as per XHR docs , we have to support PUT,DELETE,HEAD as well.

2021-11-11 10:17 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +    networkRequest->responseBuffer_  = (char *) malloc(networkRequest->contentSize_);
should this malloc be contentSize+1 ?

2021-11-11 10:17 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +        if(!(networkRequest->useIncrementalUpdates_ && (networkRequest->responseType_ == "text")))
is the responseType check required here ? since in sendData we are already checking it

2021-11-11 10:17 UTC, pprabhu-ng commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +          connectionList_.erase(networkRequest->requestId_);
should we release the memory allocated for networkRequest->responseBuffer_   before remove from the list?
If yes, same to be done in abort function as well.

2021-11-11 15:17 UTC, munezbn requested changes

2021-11-11 15:17 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +      return jsi::Value((int)CURL_RETURN_FAILURE);
In all the error case will need to cleanup. Else there will be memory leak for networkRequest object and also the curl handle is unused.

2021-11-11 15:17 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +    // TODO: responseText property needs to get and pass the value in the didReceiveNetworkIncrementalData event
move this TODO comment inside "text" response type check

2021-11-11 15:17 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
> +      curl_easy_setopt(curl, CURLOPT_TIMEOUT, timeout);
This code can be simplified like we discussed.

2021-11-11 15:17 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.cpp
>    CURL *curl;
Initialize this with nullptr.

2021-11-11 15:17 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.h
> +    :self_(self)
initialize curl with nullptr

2021-11-11 15:27 UTC, munezbn requested changes

2021-11-11 15:27 UTC, munezbn commented on ReactSkia/modules/platform/libcurl/RSkNetworkingModule.h
> +    free(responseBuffer_);
You we will need to check the pointer before freeing

2021-11-12 09:48 UTC, pprabhu-ng approved these changes

2021-11-12 10:00 UTC, munezbn approved these changes

2021-11-12 10:02 UTC, merged