Supported Transform Props on Native Side
nagra-opentv/react-native-skia pull request #60
Opened 2021-11-19 12:04 UTC by shefayaparwin

1. Implemented Scale, Rotate, Translate & Skew.
2. Anchor point of transformation is center of teh frame in reference to React Native iOS & Android
3. Consider transformed frame co-ordinates in the dirtyRect Region.

2021-11-19 12:21 UTC, pprabhu-ng requested changes

2021-11-19 12:21 UTC, pprabhu-ng commented on rns_shell/compositor/layers/Layer.cpp
>      context.canvas->translate(frame_.x(), frame_.y());
translate operation is probably redundant here

2021-11-19 15:37 UTC, munezbn approved these changes

2021-11-22 04:22 UTC, pprabhu-ng approved these changes

2021-11-22 04:22 UTC, merged