Text input props
nagra-opentv/react-native-skia pull request #65
Opened 2021-11-25 11:41 UTC by martunjai

2021-11-26 07:19 UTC, pprabhu-ng requested changes

2021-11-26 07:19 UTC, pprabhu-ng commented on ReactSkia/LegacyNativeModuleRegistry.cpp
> +        "placeholderTextColor","UIColor")(
Using of UIColor, since this is iOS color type , can we add a comment here mentioning that since we are using platform type as iOS for app bundle , iOS type is been used.

2021-11-26 07:19 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +#include "ReactSkia/views/common/RSkConversion.h"
header file includes to follow coding guidelines

2021-11-26 07:19 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +  paraStyle.setMaxLines(SINGLE_LINE);
max number of lines should be derived from multiline & numberOfLines prop value ?
If we are targetting single line for now , then better to rename the define as NUMBER_OF_LINES ?

2021-11-26 07:19 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +  do {
is do while required here ?

2021-11-26 07:19 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +void RSkComponentTextInput::updateComponentProps( const ShadowView &newShadowView, bool forceUpadate) {
this function declaration has changed in latest code, a invalidate mask is required to be returned here.please sync with latest code

2021-11-26 07:19 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +    if (textInputProps.defaultValue.size()) {
should this be else if ?

2021-11-26 07:19 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.h
> +  std::string string_{};
better to have proper names for the variables for string , text and color ; 
based on its functionality

2021-11-26 07:19 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +      color_ = textInputProps.placeholderTextColor;
is there any default value required to added for color ?

2021-11-26 16:37 UTC, pprabhu-ng requested changes

2021-11-26 16:37 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
>    return RnsShell::LayerInvalidateNone;
we should add a check if value/default value/placeholder has changed,then return should be LayerPaintValidate else None

2021-11-26 16:37 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.h
> +  std::string displayString_{};
please add comments on displaySTring and textString usage

2021-11-26 16:37 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +    textString_ = displayString_;
we can have a discussion on this usage of two strings here

2021-12-01 16:49 UTC, pprabhu-ng requested changes

2021-12-01 16:49 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +  RNS_LOG_INFO("called constructor");
is this logs required  in constructor ?

2021-12-01 16:49 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +//CHECK with PO/SM to include in class
comment is valid ?

2021-12-01 16:49 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +  }
else if to be part of same line as per coding guidelines

2021-12-01 16:49 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentTextInput.cpp
> +  if ((textString == displayString_) && (placeholderString_ == displayString_)) {
displayString_ will never be equal to placeholderString right ?

2021-12-02 09:32 UTC, pprabhu-ng approved these changes

2021-12-03 05:30 UTC, shefayaparwin commented on ReactSkia/components/RSkComponentTextInput.cpp
> -  ShadowMetrics shadowMetrics{};
As draw shadow is not handled, suggest to remove this shadowMetric handling, as that is removed is one other PR in review. ON merge both will leads to compilation error

2021-12-03 07:03 UTC, shefayaparwin approved these changes

2021-12-03 09:28 UTC, chatrapathi06 approved these changes

2021-12-03 12:24 UTC, pprabhu-ng requested changes
Please rebase the dev branch and ensure the commit logs are in sync with main branch.

2021-12-08 13:04 UTC, munezbn approved these changes

2021-12-08 13:08 UTC, pprabhu-ng approved these changes

2021-12-08 13:09 UTC, merged