Dimensions support get method
nagra-opentv/react-native-skia pull request #86
Opened 2022-01-24 06:02 UTC by ddesai96

Dimensions support for get method to receive window/screen dimensions, scale, and fontScale properties.

2022-01-24 10:29 UTC, munezbn requested changes

2022-01-24 10:29 UTC, munezbn commented on ReactSkia/core_modules/RSkDeviceInfo.cpp
> +  SkSize screenSize = RnsShell::PlatformDisplay::sharedDisplay().screenSize();
Validate count (argument count) like we do in other modules wrapper.

2022-01-24 10:29 UTC, munezbn commented on ReactSkia/JSITurboModuleManager.cpp
> +
Was this by mistake or intentional

2022-01-25 05:16 UTC, munezbn approved these changes

2022-01-25 06:03 UTC, pprabhu-ng approved these changes

2022-01-25 06:04 UTC, pprabhu-ng requested changes
the test app should go under packages/react-native-skia/modules/dimensions/

2022-02-02 07:31 UTC, pprabhu-ng approved these changes

2022-02-02 07:32 UTC, merged