TextInput - Display cursor when text input is in editing mode
nagra-opentv/react-native-skia pull request #90
Opened 2022-02-21 11:10 UTC by martunjai

Updated code to Display cursor when text input is in editing mode only.

2022-02-23 07:40 UTC, pprabhu-ng requested changes
Line 205 , when value prop is defined and Enter key is pressed to exit editing mode. This case is still not handled. 
Please also verify the changes with value prop

2022-02-23 11:54 UTC, chatrapathi06 approved these changes

2022-02-23 12:41 UTC, pprabhu-ng approved these changes

2022-02-24 07:58 UTC, munezbn approved these changes

2022-02-24 08:01 UTC, merged